version: '3.9'

services:
  php:
    build:
       ./php
    ports:
      - 80:80
    depends_on:
      - mysql

  mysql:
    image: mysql:5.6
    volumes:
      - ./mysql:/var/lib/mysql/
    env_file:
      db.env
    ports:
      - 3306:3306
